

title: Probability on a napkin
email: on234@cam.ac.uk
description: >- 
  Probability, Philosophy, Climate and more.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oremnirv.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: omer_nivron
github_username:  oremnirv

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

disqus:  
   shortname: (https-oremnirv-github-io)
